#!/bin/python3
# -*- coding: utf-8 -*-
#
# kevin - by:proxlu

# Código para desenvolvimento
# Caso deseje kevin para uso pessoal, baixe nesse link: https://github.com/proxlu/kevin/releases/download/cli

import sys

# Pega toda entrada
arg = ' '.join(sys.argv[1:])

import requests
from bardapi.constants import SESSION_HEADERS
from bardapi import Bard, ChatBard

# Token do BARD
token = ''

# Sessões de cookies
session = requests.Session()
session.headers = SESSION_HEADERS
session.cookies.set('__Secure-1PSID', token)
session.cookies.set('__Secure-1PSIDTS', '<VALUE>')
session.cookies.set('__Secure-1PSIDCC', '<VALUE>')

# Estrutura principal
if arg:
  bard = Bard(token=token, session=session)
  text = bard.get_answer(arg)['content']
  url = bard.get_answer(arg)['images']

  print('\033[34m\033[1m')
  print(text)

  if url:
    if '[Image' in text.split() or '[Imagem' in text.split() or '[Imagen' in text.split():
      print(' Image links:', url)
  print('\033[39m\033[0m')

else:
  ChatBard(token=token, session=session).start()
